configured_endpoints: 97
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stainless-commons/spotify-196cd256e2787b707fa4a7b6b8f79d6bfd23cca600397dedc0bcb4cf0f1ae4e2.yml
openapi_spec_hash: 87fe8dfdf309eaa872162d50af8ede8f
config_hash: cf96e57fe38f6f4a410a37130ace2e38
